- setup.py
The command bdist_egg is currently not available. This patch will fix that.
> import setup from setuptools to enable bdist_egg

- js2py/evaljs.py
- js2py/legecy_translators/constants.py
- js2py/translators/translating_nodes.py
- js2py/translators/translator.py
- testCompilationPlan.py
At times there's a need to evaluate a lot of expressions that have the same structure. For such cases it's possible to avoid ast parsing by creating and re-using a compilation plan.
See testCompilationPlan.js in the repo for example and demonstration.
> Compilation plans

- js2py/translators/pyjsparser.py
I ran into troubles using a JavaScript regexp like /[a\-z]/ where the "-" is meant to be literal. Adding "-" to the REGEXP_SPECIAL_SINGLE set fixes this (for me).
> include hyphen in regexp special single chars

- js2py/prototypes/jsarray.py
When supplying a custom sort function to `Array.prototype.sort()` js2py tells me "name 'this' is not defined". 
There are several py3/six compatibility errors in `sort(cmpfn)` in `jsarray.py`. Somehow the list comprehension loses the `this` scope which is most hackishly resolved by not using a list comprehension, but there may be a more elegant solution.
Testcase:
```
/*---
info: > Sort should work with custom compare function in python3 too
description: Test custom compare function in python3
---*/
var myComparefn = function(x,y) {
return x < y ? -1 : (x > y) ? 1 : 0;
};
var x = new Array(2,1,3);
x.sort(myComparefn);
//CHECK#1
if (!(x[0] === 1 && x[1] === 2 && x[2] === 3)) {
$ERROR('#1: var x = new Array(2,1,3); x.sort(myComparefn); !(x[0] === 1 && x[1] === 2 && x[2] === 3). Actual: ' + …
```
> fix Array.prototype.sort() in python3

- js2py/base.py
- js2py/constructors/jsfloat32array.py
- js2py/constructors/jsfloat64array.py
- js2py/constructors/jsint16array.py
- js2py/constructors/jsint32array.py
- js2py/constructors/jsint8array.py
- js2py/constructors/jsuint16array.py
- js2py/constructors/jsuint32array.py
- js2py/constructors/jsuint8array.py
- js2py/constructors/jsuint8clampedarray.py
Seems to work better than previous pull request.
```
>>> import js2py
>>> js2py.eval_js('a = new ArrayBuffer(8); b = new Int32Array(a); c = new Int16Array(a); b[0] = 5; c[0]')
5
```
```
>>> a = js2py.eval_js('new Uint8ClampedArray(5)')
>>> a[0] = 258
>>> a[0]
255
```
```
>>> js2py.eval_js('a = new Int32Array([335544318]); a[0]<<6')
-128
>>> js2py.eval_js('a = new Uint16Array([335544318]); a[0]<<6')
4194176
>>> js2py.eval_js('a = new Uint8Array([335544318]); a[0]<<6')
16256
```
```
>>> js2py.eval_js('a = new ArrayBuffer(16); new Uint32Array(a)')
[0, 0, 0, 0]
>>> js2py.eval_js('a = new ArrayBuffer(16); new Uint32Array(a,4)')
[0, 0, 0]
>>> js2py.eval_js('a = new ArrayBuffer(16); new Uint32Array(a,8,1)')
[0]
>>> js2py.eval_js('a = new ArrayBuffer(16); new Uint32Array(a,0,2)')
[0, 0]
```
> TypedArray fixes

- js2py/node_import.py
- simple_test.py
such as `js2py.require('crypto-js/aes')`
> js2py.require support subpath

- js2py/internals/func_utils.py
Partial fix for #113 (`Object.getOwnPropertyDescriptor` still not dealt with)
> Add space argument to recursive convert_to_js_type calls

- js2py/translators/translator.py
- tests/run.py
Hello,
This is a little patch to fix those warnings:
```python
translators/translator.py:19: DeprecationWarning: invalid escape sequence \.
CP_NUMERIC_PLACEHOLDER.replace('%i', '([0-9\.]+)')
translators/translator.py:33: DeprecationWarning: invalid escape sequence \.
CP_STRING_PLACEHOLDER.replace('%i', '([0-9\.]+)')
tests/run.py:99: DeprecationWarning: invalid escape sequence \*
self.raw_info = re.search('/\*---(.+)---\*/', self.raw, re.DOTALL).groups()[0].strip()
```
Signed-off-by: Mickaël Schoentgen <contact@tiger-222.fr>
> Fix several DeprecationWarning: invalid escape sequence

- js2py/prototypes/jsfunction.py
Not sure why but at least on `Python 3.7.2`, the injected `arguments` hack was causing an unknown reference when used in the list comprehension. Explicitly bringing it into the local scope (copying from `call`) seemed to fix the issue.
Tested with
<details>
<summary>JS code</summary>
```javascript
function t(x, y) {
return x + y;
}
var u = t.call(void 0, 11, 12);
console.log('u: ' + u);
var v = t.apply(void 0, [11, 12]);
console.log('v: ' + v);
var w = t.bind(void 0, 11);
console.log('w: ' + w(12));
function s(x, y) {
return x + y + this.z;
}
var a = s.call({z: 10}, 11, 12);
console.log('a: ' + a);
var b = s.apply({z: 10}, [11, 12]);
console.log('b: ' + b);
var c = s.bind({z: 10}, 11);
console.log('c: ' + c(12));
```
</details>
<details>
<summary>Transpiled python</summary>
```python
from …
```
> Fix injected local 'arguments' not working in list comprehension in bind.

- .travis.yml
- js2py/utils/injector.py
The arguments to `CodeType` have changed, but a `replace` method was introduced that we can use.
Fixes #175.
Adds Python 3.7 and 3.8 to Travis CI. Have to then remove support for unsupported Python versions (see https://devguide.python.org/#status-of-python-branches).
> Fix injector for Python 3.8+.

- js2py/internals/speed.py
- js2py/legecy_translators/constants.py
- js2py/legecy_translators/exps.py
- js2py/legecy_translators/flow.py
- js2py/legecy_translators/functions.py
- js2py/legecy_translators/jsparser.py
- js2py/legecy_translators/nodevisitor.py
- js2py/legecy_translators/objects.py
- js2py/legecy_translators/translator.py
This PR superseeds #166 
The original PR only fixed the call of a print function in one file (one imported during install).
This PR fixes all issues found by running pythons compileall on the source:
```python3 -m compileall .```
Fix #106 
Fix #160
> Fix print functions and a python2 only import

- js2py/base.py
fix error msg from python function beacuase python3+ does not support  e.message , just supports str(e) and also python2+ too
fix #197
> Exception class - attribute message Python3

- js2py/constructors/jsdate.py
- js2py/internals/constructors/jsdate.py
These have all been tested, but may need some details adjusted to fit with existing code.
There is an implementation error with MakeDay/MakeTime, where it expects PyJs objects while setMilliseconds/setUTCMilliseconds send integers. The quick fix was just to convert those arguments for now as I'm not sure what's intended and I can't really change this behavior cleanly without modifying functions clearly laid out in the spec. At the same time, these DatePrototype setters are also clearly defined..
> Complete all setters!

- js2py/constructors/jsdate.py
- js2py/internals/constructors/jsdate.py
Removed the Python2 workaround
> Fix Date.UTC,  Workaround datetime.datetime.utcfromtimestamp limitation

- js2py/constructors/time_helpers.py
- js2py/internals/base.py
- js2py/internals/constructors/time_helpers.py
This was found in issue #215 reproducible just by loading ssf.js.
```
Traceback (most recent call last):
File "test.py", line 28, in <module>
context.execute(js)
File "C:\Python38\Js2Py-master\js2py\evaljs.py", line 199, in execute
exec (compiled, self._context)
File "<EvalJS snippet>", line 2174, in <module>
File "C:\Python38\Js2Py-master\js2py\base.py", line 949, in __call__
return self.call(self.GlobalObject, args)
File "C:\Python38\Js2Py-master\js2py\base.py", line 1464, in call
return Js(self.code(*args))
File "<EvalJS snippet>", line 1541, in PyJs_make_ssf_0_
File "C:\Python38\Js2Py-master\js2py\constructors\jsdate.py", line 149, in date_constructor
return date_constructor2(*args)
File "C:\Python38\Js2Py-master\js2py\constructors\jsdate.py", line 181, in date_constructor2 …
```
> [WIN] Workaround utcfromtimestamp in DaylightSavingTA

- js2py/constructors/jsdate.py
I'm working on a project where I have a large JS codebase that runs on V8. It would be very problematic to transform the code to support RFC3339 date format.
With these simple changes Js2Py, would support three very natural date input formats used in the JavaScript world.
There is the dateutil module that is very powerful and can be plugged in and support many date(time) formats, however, I didn't want to add more dependencies to the project.
In any case, I think this is a good start and it's something that doesn't seem to break compatibility, and at the same time it's easy to maintain.
- New type of date format:
```python
>>> js2py.eval_js("""console.log(new Date('01/01/2010'))""")
'Thu Dec 31 2009 19:00:00 GMT-0500 (EST)'
```
- A bad date format:
```python
>>> …
```
> Adds basic support for JS input date formats

- setup.cfg
future releases of setuptools will not support "description-file"
'''/usr/lib/python3.9/site-packages/setuptools/dist.py:642:
UserWarning: Usage of dash-separated 'description-file'
will not be supported in future versions. Please use the
underscore name 'description_file' instead'''
warning discovered on setuptools, version 56.0.0
Signed-off-by: Maciej Barć <xgqt@riseup.net>
> setup.cfg: description-file -> description_file

- js2py/evaljs.py
Function translate_file uses function write_file_contents. However, function write_file_contents doesn't write Python code while using UTF-8 to encode. It will cause problems after translate JS file with special strings ( e.g., Chinese) to Python file. Error will be raised when importing objects from the Python file.
Just like function get_file_contents, used codecs.open to fix the problem.
> Found BUG of translate_file and fixed

- js2py/internals/prototypes/jsstring.py
- js2py/prototypes/jsstring.py
- tests/run.py
Thanks for an amazing JS VM/translator! I really appreciate the work you've done to make this so functional.
This fixes #260. These tests now pass on both the translator and the VM:
- String/prototype/replace 15.5.4.11_A2_T3
- String/prototype/replace 15.5.4.11_A2_T8
**Note**: when running the tests, `run.py` looked for a file named `node_failed.txt`. I used an empty file to allow the tests to run; should this be checked into the repo?
> Fix String.prototype.replace with `$&` replacement text

- .github/workflows/tests.yml
Adding github actions workflow.
Windows tests disabled due issue with node packages.
> Add github actions workflow
